name: project_2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  bottom_bar: ^2.0.2
  flutter_map: ^2.1.1
  google_maps_flutter: ^2.1.10
  geolocator: ^9.0.1
  # geocoding: ^2.0.4

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
   - assets/
   - assets/hotels/


  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf    